package vrm0

import "github.com/thara/go-vrm-migrate/vrm0/internal"

type SecondaryAnimation = internal.VrmSecondaryanimationSchemaJson

type SecondaryAnimationSpring = internal.VrmSecondaryanimationSpringSchemaJson

type SecondaryAnimationSpringGravityDir = internal.VrmSecondaryanimationSpringSchemaJsonGravityDir

type SecondaryColliderGroup = internal.VrmSecondaryanimationCollidergroupSchemaJson

type SecondaryColliderGroupCollidersElem = internal.VrmSecondaryanimationCollidergroupSchemaJsonCollidersElem

type SecondaryColliderGroupCollidersElemOffset = internal.VrmSecondaryanimationCollidergroupSchemaJsonCollidersElemOffset
